name: monkey_ad_app
description: "Welcome to Ad Monkey Madness! Click the button to see an ad and enjoy a dancing monkey with confetti and sound effects."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3+4

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.2.0
  google_mobile_ads: ^5.1.0
  lottie: ^3.1.2
  confetti: ^0.7.0
  provider: ^6.1.2
  audioplayers: ^6.0.0
  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.6
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  change_app_package_name: ^1.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/
